version: '3'
services:
  php_:
    build: ./php
    image: php:latest
    container_name: php_
    hostname: "php"
    volumes:
      - ./blueprint_test:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - mysql__

  mysql__:
    image: mariadb:10.2
    container_name: mysql__
    restart: unless-stopped
    tty: true
    ports:
      - "33306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: Djony
      MYSQL_PASSWORD: Djony!!
      MYSQL_ROOT_PASSWORD: Djony
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
    read_only: false

  nginx__:
    build: ./nginx
    image: nginx:latest
    container_name: nginx__
    hostname: "nginx"
    ports:
      - "100:80"
    volumes:
      - ./blueprint_test:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_
